# Generated by Django 4.2.7 on 2026-02-06 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('account', 'Account'), ('item', 'Item'), ('currency', 'Currency'), ('topup', 'Top Up'), ('gift_card', 'Gift Card'), ('boosting', 'Boosting')], max_length=20)),
                ('game_title', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('price_pkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('sold_out', 'Sold Out'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'category'], name='listings_li_status_81a7f1_idx'), models.Index(fields=['price_pkr'], name='listings_li_price_p_583780_idx')],
            },
        ),
    ]
