# Generated by Django 4.2.7 on 2026-02-07 00:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_listing_catalog(apps, schema_editor):
    Listing = apps.get_model("listings", "Listing")
    Game = apps.get_model("listings", "Game")
    GameCategoryOption = apps.get_model("listings", "GameCategoryOption")

    category_labels = {
        "account": "Account",
        "item": "Item",
        "currency": "Currency",
        "topup": "Top Up",
        "gift_card": "Gift Card",
        "boosting": "Boosting",
    }

    for listing in Listing.objects.all().iterator():
        game_name = (listing.game_title or "").strip()
        if not game_name:
            continue

        game, _ = Game.objects.get_or_create(
            name=game_name,
            defaults={"is_active": True},
        )

        canonical_category = listing.category
        display_name = category_labels.get(canonical_category, "Category")
        game_category, _ = GameCategoryOption.objects.get_or_create(
            game=game,
            canonical_category=canonical_category,
            display_name=display_name,
            defaults={"is_active": True, "sort_order": 0},
        )

        Listing.objects.filter(pk=listing.pk).update(
            game_id=game.pk,
            game_category_id=game_category.pk,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GameCategoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_category', models.CharField(choices=[('account', 'Account'), ('item', 'Item'), ('currency', 'Currency'), ('topup', 'Top Up'), ('gift_card', 'Gift Card'), ('boosting', 'Boosting')], max_length=20)),
                ('display_name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_options', to='listings.game')),
            ],
            options={
                'ordering': ('game__name', 'sort_order', 'display_name'),
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.game'),
        ),
        migrations.AddField(
            model_name='listing',
            name='game_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.gamecategoryoption'),
        ),
        migrations.AddIndex(
            model_name='gamecategoryoption',
            index=models.Index(fields=['game', 'canonical_category', 'is_active'], name='listings_ga_game_id_114a2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamecategoryoption',
            unique_together={('game', 'display_name')},
        ),
        migrations.RunPython(backfill_listing_catalog, noop_reverse),
    ]
