# Generated by Django 4.2.7 on 2026-02-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('deposit_credit', 'Deposit Credit'), ('withdrawal_hold', 'Withdrawal Hold'), ('withdrawal_release', 'Withdrawal Release'), ('withdrawal_paid', 'Withdrawal Paid'), ('order_payment', 'Order Payment'), ('order_sale_hold', 'Order Sale Hold'), ('order_sale_release', 'Order Sale Release'), ('order_fee_capture', 'Order Fee Capture'), ('order_refund', 'Order Refund'), ('adjustment', 'Adjustment')], max_length=30),
        ),
    ]
