# Generated by Django 4.2.7 on 2026-02-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_walletledgerentry_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositticket',
            name='proof_note',
        ),
        migrations.AddField(
            model_name='depositticket',
            name='receipt_file',
            field=models.FileField(blank=True, upload_to='deposit_receipts/'),
        ),
        migrations.AddField(
            model_name='depositticket',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='depositticket',
            name='payment_method',
            field=models.CharField(choices=[('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash'), ('bank_transfer', 'Bank Transfer'), ('sadapay', 'SadaPay'), ('nayapay', 'NayaPay')], max_length=30),
        ),
    ]
