# Generated by Django 4.2.7 on 2026-02-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_depositticket_proof_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_method',
            field=models.CharField(choices=[('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash'), ('bank_transfer', 'Bank Transfer'), ('sadapay', 'SadaPay'), ('nayapay', 'NayaPay')], max_length=30),
        ),
    ]
